title: Fuzzy-octo-shame
description: 2D platformer skeleton built with LWJGL and fork of Slick2D
google_analytics: UA-57378181-3
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
